apiVersion: v1
kind: Service
metadata:
  name: jmeter-grafana
  labels:
    app: jmeter-grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: jmeter-grafana
  type: LoadBalancer
  
---

apiVersion: v1
kind: Service
metadata:
  name: image-renderer
  labels:
    app: image-renderer
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: image-renderer
  type: ClusterIP
