# Kubernete definition file
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-grafana-frontend
  labels:
    app: jmeter-grafana
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: jmeter-grafana
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-grafana
  labels:
    app: jmeter-grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: jmeter-grafana
  type: NodePort
