apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  labels:
    app: influxdb-jmeter
data:
  load_test: |
    #!/bin/bash
    # Script created to invoke jmeter test script with the slave POD IP addresses
    # Script should be run like: ./load_test "path to the test script in jmx format"
    /jmeter/apache-jmeter-*/bin/jmeter -n -t $1 -l $2 \
    -Dserver.rmi.ssl.disable=true \
    -R `getent ahostsv4 jmeter-slaves-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`
  generate_report: |
    #!/bin/bash
    # To Generate a JMeter HTML report from a JMeter test log (jtl) file.
    # Argument 1 is the jtl filename
    # Argument 2 is the output report directory
    /jmeter/apache-jmeter-*/bin/jmeter -g $1 -o $2 \
    -Jjmeter.reportgenerator.overall_granularity=1000
